/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenjualangas;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author TOSHIBA DC
 */
public class help extends javax.swing.JInternalFrame {

    /**
     * Creates new form barang
     */
    public help() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        waBT = new javax.swing.JButton();
        fbBT = new javax.swing.JButton();
        gmailBT = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1160, 570));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Help ???");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 170, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 76, 410, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1160, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(102, 204, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        waBT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        waBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Whatsapp_37229.png"))); // NOI18N
        waBT.setText("WHASTAPP");
        waBT.setBorder(null);
        waBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                waBTMouseEntered(evt);
            }
        });
        waBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waBTActionPerformed(evt);
            }
        });
        jPanel3.add(waBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 275, 67));

        fbBT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        fbBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-facebook-28.png"))); // NOI18N
        fbBT.setText("FACEBOOK");
        fbBT.setBorder(null);
        fbBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbBTMouseEntered(evt);
            }
        });
        fbBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbBTActionPerformed(evt);
            }
        });
        jPanel3.add(fbBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 275, 67));

        gmailBT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        gmailBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gmail.png"))); // NOI18N
        gmailBT.setText("GMAIL");
        gmailBT.setBorder(null);
        gmailBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gmailBTMouseEntered(evt);
            }
        });
        gmailBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailBTActionPerformed(evt);
            }
        });
        jPanel3.add(gmailBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 275, 67));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 390, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fbBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbBTMouseEntered
        // TODO add your handling code here:
         fbBT.setBackground(new Color(102,204,255));
        fbBT.setForeground(Color.black);
    }//GEN-LAST:event_fbBTMouseEntered

    private void gmailBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmailBTMouseEntered
        // TODO add your handling code here:
         gmailBT.setBackground(new Color(102,204,255));
        gmailBT.setForeground(Color.black);
    }//GEN-LAST:event_gmailBTMouseEntered

    private void waBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waBTMouseEntered
        // TODO add your handling code here:
         waBT.setBackground(new Color(102,204,255));
        waBT.setForeground(Color.black);
    }//GEN-LAST:event_waBTMouseEntered

    private void gmailBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailBTActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://mail.google.com/mail").toURI());
            dispose();
        }catch(Exception ex){
            System.out.println(ex);

        }
    }//GEN-LAST:event_gmailBTActionPerformed

    private void fbBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbBTActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://id-id.facebook.com/").toURI());
            dispose();
        }catch(Exception ex){
            System.out.println(ex);

        }
        
    }//GEN-LAST:event_fbBTActionPerformed

    private void waBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waBTActionPerformed
        // TODO add your handling code here:
           try{
            Desktop.getDesktop().browse(new URL("https://web.whatsapp.com/").toURI());
            dispose();
        }catch(Exception ex){
            System.out.println(ex);

        }
    }//GEN-LAST:event_waBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fbBT;
    private javax.swing.JButton gmailBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton waBT;
    // End of variables declaration//GEN-END:variables
}
